name: PROJECT_NAME_PLACEHOLDER_env
channels:
  - conda-forge
dependencies:
  # Build Tools
  - cxx-compiler
  - cmake
  - make
  - gdb

  # Documentation Tools
  - doxygen          # Extracts API comments from C++
  - sphinx           # Builds the documentation website
  - breathe          # Bridge between Doxygen and Sphinx
  - sphinx_rtd_theme # The standard "ReadTheDocs" theme
  
  # Dependencies
  - spdlog   # Logging
  - gtest    # Testing
